hmcts/camunda-bpm

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- docker-compose.yml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/CamundaApplication.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/app/AuthorizationHelper.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/AccessControl.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/ConfigProperties.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/GroupConfig.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityConfig.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/context/SpringContext.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecurityAuthenticationProvider.java
- src/main/resources/application.yaml
Did some basic refactoring to parameterise  properties
```
[ ] Yes
[x] No
```
> Basic refactoring to parameterise..

- build.gradle
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/CamundaApplication.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/ConfigProperties.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityConfig.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecurityAuthenticationProvider.java
- src/main/resources/application.yaml
Disabling spring security will hand over control to camunda authentication.
```
[ ] Yes
[x] No
```
> Adding option to disable security

- Jenkinsfile_CNP
- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/requirements.yaml
- charts/camunda-bpm/values.preview.template.yaml
- charts/camunda-bpm/values.yaml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityConfig.java
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/data/migration/FlywayNoOpStrategyTest.java
> Adding Jenkins and chart

- Jenkinsfile_CNP
- build.gradle
- charts/camunda-bpm/values.preview.template.yaml
- config/owasp/suppressions.xml
- docker-compose.yml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityAnonymousConfig.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityConfig.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecurityAuthenticationProvider.java
- src/main/resources/application.yaml
- src/smokeTest/java/uk/gov/hmcts/reform/camunda.bpm/ApplicationHealthTest.java
- src/smokeTest/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecutiryAuthenticationProviderTest.java
- src/test/resources/application.yaml
> Add tests and validate PR build

- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.preview.template.yaml
- charts/camunda-bpm/values.yaml
- src/main/resources/bootstrap.yaml
> Add secrets config for database password

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.aat.template.yaml
- charts/camunda-bpm/values.yaml
> Fix AAT Build

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
- infrastructure/db.tf
- src/main/resources/bootstrap.yaml
> fix db migration secrets

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
- infrastructure/db.tf
- src/main/resources/bootstrap.yaml
> fix db pwd secret name

- .gitignore
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.preview.template.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
AB#1044
```
[ ] Yes
[ ] No
```
> Changes for UI deployment

- src/main/resources/db/migration/V2__postgres_engine_7.11_to_7.12.sql
- src/main/resources/db/migration/V3__postgres_engine_7.12_to_7.13.sql
AB#1044
```
[ ] Yes
[ ] No
```
> Add DB migration for upgrade

- src/main/resources/application.yaml
AB#1044
```
[ ] Yes
[ ] No
```
> Add RBAC for camunda

- src/main/resources/application.yaml
AB#1044
```
[ ] Yes
[ ] No
```
> Add team RBAC for Camunda

- infrastructure/main.tf
> Add camunda admin password to kv

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
> Override default Camunda password

- charts/camunda-bpm/Chart.yaml
> Upgrade chart

- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.preview.template.yaml
- charts/camunda-bpm/values.yaml
> Fix db connection

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityApiAnonymousConfig.java
- src/main/resources/application.yaml
> Needs enabling anonymous requests explicitly

- src/main/resources/application.yaml
> Authorize service

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-280
Updated camunda groups
```
[ ] Yes
[ x ] No
```
> updated camunda group names

- build.gradle
After updates, seeing - "java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException"
Camunda is still up but looks to be affecting performance so want to get this fixed. 
Related stack overflow https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio
```
[ ] Yes
[ x] No
```
> Add in missing jaxb classes

- infrastructure/vault.tf
- src/main/resources/application.yaml
Change from dcd_platformengineering AD group to dcd_platformengineering.
Naming also updated
```
[ ] Yes
[x ] No
```
> Switch from rpe to platops, including AD groupid

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-242
Add wa-camunda-pipeline-upload  to list of s2s authorised
```
[ ] Yes
[ x] No
```
> Add wa-camunda-pipeline-upload

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
- src/main/resources/application.yaml
- src/test/resources/application.yaml
Added feature flag 
```
[ ] Yes
[x ] No
```
> Feature flag for task autoconfiguration

- src/integrationTest/java/uk/gov/hmcts/reform/camunda/bpm/clients/TaskConfigurationServiceApiTest.java
- src/integrationTest/resources/application-integration.yaml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
- src/main/resources/application.yaml
- src/test/resources/application.yaml
Change wiremock port
```
[ ] Yes
[ x] No
```
> Change wiremock port

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/FeignRetryPolicy.java
Prints exception
```
[ ] Yes
[x ] No
```
> Print exception

- Jenkinsfile_CNP
Fix s2s secret
```
[ ] Yes
[ x] No
```
> Fix s2s secret

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
Added event trigger check
```
[ ] Yes
[x ] No
```
> Added event trigger check

- Jenkinsfile_CNP
- charts/camunda-bpm/Chart.yaml
To Sync infrastructure
```
[ ] Yes
[x] No
```
> Sync infra to all envs, update helm chart

- infrastructure/vault.tf
> move to vault master

- infrastructure/main.tf
https://APPLICATION ls.hmcts.net/jira/browse/DTSPO-2371
> DTSPO-2371 Creating AppInsight  

- src/main/resources/application.yaml
> remove default password

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
- src/main/resources/db/migration/V4_postgres_engine_7.13_patch_7.13.4_to_7.13.5_1.sql
- src/main/resources/db/migration/V5_postgres_engine_7.13_patch_7.13.4_to_7.13.5_2.sql
- src/main/resources/db/migration/V6_postgres_engine_7.13_patch_7.13.5_to_7.13.6.sql
- src/main/resources/db/migration/V7_postgres_engine_7.13_to_7.14.sql
- src/main/resources/db/migration/V8_postgres_engine_7.14_to_7.15.sql
> Upgrade DB to 7.15

- src/main/resources/application.yaml
> Add empty defaults for oauth2 client secrets

- src/main/resources/application.yaml
> try import config on springauth profile

- build.gradle
> fixing jaxb errors

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
> Adding appinssights

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CMC-1545
```
[ ] Yes
[x] No
```
> Added Civil group

- README.md
> Add basic optimize docs

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
https://tools.hmcts.net/jira/browse/RWA-506
Added error log to support task unconfigured alerts
```
[ ] Yes
[x ] No
```
> Add error log

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-617
```
[ ] Yes
[x ] No
```
> Auto configure set to true by default

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfigurationTest.java
https://tools.hmcts.net/jira/browse/RWA-582
Added Event listener condition and added more events for delete and complete to add a new local variable
```
[ ] Yes
[ x] No
```
> RWA-582: Completion / Cancellation: Update Event Bridge to add task variable

- build.gradle
Bump commons-compress to 1.21
Bump tomcat version to 9.0.50
Bump camunda-bpm-spring-boot-starter-webapp-ee to 7.15.4-ee
```
[ ] Yes
[x ] No
```
> Fix CVEs - Update dependencies

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfigurationTest.java
Add cft task state to unconfigured to create event
```
[ ] Yes
[ x] No
```
> Add cft task state to unconfigured to create event

- Jenkinsfile_CNP
- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.preview.template.yaml
- charts/camunda-bpm/values.yaml
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/camunda/bpm/clients/TaskConfigurationServiceApiTest.java
- src/integrationTest/resources/application-integration.yaml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/clients/TaskConfigurationServiceApi.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/FeignClientSnakeCaseConfiguration.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationServiceTest.java
- src/test/resources/application.yaml
- src/testUtils/java/uk/gov/hmcts/reform/camunda/bpm/SpringBootIntegrationBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-692
> point to task-management-api

- charts/camunda-bpm/Chart.yaml
Up the java chart version
```
[ ] Yes
[ ] No
```
> Refactor:Up the java chart version

- build.gradle
- charts/camunda-bpm/Chart.yaml
- config/owasp/suppressions.xml
refactor:resolve dependency issues
```
[ ] Yes
[ ] No
```
> refactor:resolve dependency issues

- build.gradle
correct repo order
```
[ ] Yes
[ ] No
```
> refactor:correct repo order

- Jenkinsfile_nightly
Tested here:
https://build.platform.hmcts.net/job/HMCTS_Nightly_Platform/job/camunda-bpm/job/nightly-dev/
Failing because of dep check
> Enable nightly build

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
Resolve dependency issue with spring boot upgrade
```
[ ] Yes
[ ] No
```
> refactor:Resolve dependency issue with spring boot upgrade

- charts/camunda-bpm/Chart.yaml
> Bump chart version

- .gitignore
- Dockerfile
- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
- infrastructure/app-insights.tf
- lib/AI-Agent.xml
- lib/applicationinsights.json
> Revert "DTSPO-6256 Update app insights and switch to Java 17"

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/FeignRetryPolicy.java
- src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/services/FeignRetryPolicyTest.java
https://tools.hmcts.net/jira/browse/RWA-1296
Expanded logging to help work out unconfigured tasks
```
[ ] Yes
[ X] No
```
> RWA-1296 Expanded logging and CVE fixes

- build.gradle
- src/main/resources/db/migration/V10__postgres_engine_7.16_to_7.17.sql
> Add migration scripts for 7.17

- Dockerfile
- build.gradle
- charts/camunda-bpm/Chart.yaml
DTSPO-6156
Migrate Camunda app to Java 17
```
[ ] Yes
[X] No
```
> DTSPO-6156 - Migrate Camunda app to Java 17

- infrastructure/aat.tfvars
- infrastructure/db.tf
- infrastructure/variables.tf
PLS DO NOT MERGE!!!!!!!
DTSPO-10069
Increase SKU and Storage on Camunda AAT DB
```
[ ] Yes
[ x] No
```
> Increase SKU and Storage on Camunda AAT DB

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1765
https://camunda.com/blog/2022/03/a-new-domain-name-for-camunda-artifactory/
```
[X] Yes
[ ] No
```
> RWA-1765 change camunda artifactory domain name

- src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
- src/test/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfigurationTest.java
[RWA-1521](https://tools.hmcts.net/jira/browse/RWA-1521)
```
[ ] Yes
[x] No
```
> RWA-1521 Camunda - Switch off Task configuration code

- config/owasp/suppressions.xml
> Suppressing CVE to continue RWA-1521 deployment

- src/main/resources/application.yaml
> Adding tenant for Private Law

- README.md
> Add new team onboarding doc

- src/main/resources/application.yaml
For adding new ET tenant.
```
[ ] Yes
[x ] No
```
> Adding ET tenant

- src/main/resources/application.yaml
> Changed ET tenant id and group id

- src/main/resources/application.yaml
> Change the tenant ID for Private Law - prl to privatelaw

- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-11298
Increase SKU on perftest to meet WA NFR
```
[ ] Yes
[ ] No
```
> Dtspo 11298 increase camunda memory

- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
[DTSPO-11298](https://tools.hmcts.net/jira/browse/DTSPO-11298)
Ups SKU of camunda database in perftest and prod to 8 vCore from 4
```
[ ] Yes
[x] No
```
> Add perftest and prod SKU override (#422)

- src/main/resources/application.yaml
N/A
- Add family public law tenant to Camunda 
```
[ ] Yes
[X] No
```
> Add FPL tenant

- infrastructure/aat.tfvars
- infrastructure/db.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
Update storage_mb on aat and prod flexible servers to match single server
```
[ ] Yes
[x] No
```
> DTSPO-13682 - Update storage_mb on aat/prod flexible

- charts/camunda-bpm/Chart.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13897
Add more properties to customise history cleanup
```
[ ] Yes
[x] No
```
> DTSPO-13897 - Update job history cleanup values

- build.gradle
- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
Update values to point to flexible server equivalents
Depends on cutover being successfully being performed as part of CHG5012055
```
[ ] Yes
[x] No
```
> DTSPO-13682 - Update values to flexible server

- infrastructure/db.tf
Delete postgres single server
Pods are now using flexible server
```
[ ] Yes
[x] No
```
> DTSPO-13692 - Delete single server

- infrastructure/provider.tf
Allow nested resource deletion
Required to delete camunda single servers
```
[ ] Yes
[x] No
```
> DTSPO-13692 - Allow nested resource deletion

- charts/camunda-bpm/Chart.yaml
- charts/camunda-bpm/values.yaml
Update values to use non v14 secret
Contents of secret are valid for flexible server
```
[ ] Yes
[x] No
```
> DTSPO-13692 - Update values

- infrastructure/db.tf
Remove v14 secrets
Non v14 secrets are now using flexible server values
```
[ ] Yes
[x] No
```
> DTSPO-13692 - Remove v14 secrets

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-14167
Update Camunda Version to fix FEEL/SCALA-01008 error
```
[ ] Yes
[x] No
```
> DTSPO-14167: Update Camunda Version

- build.gradle
Reverts hmcts/camunda-bpm#572
see https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1686845130694229
> Revert "DTSPO-14167: Update Camunda Version"

- infrastructure/aat.tfvars
- infrastructure/db.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-14429
Removed old single server var settings that don't apply to Flex Server
Updated the PG Server configuration values to improve performance on Linux-based Flexserver configuration
```
[ ] Yes
[x ] No
```
> Dtspo 14429

- config/owasp/suppressions.xml
Extend the suppression of the jackson databind CVE
```
[ ] Yes
[ x] No
```
> Extend suppression of CVE-2023-35116

- config/owasp/suppressions.xml
Extend suppression for tomcat embed websocket
```
[ ] Yes
[ x] No
```
> Extend suppressions for tomcat embed websocket

- build.gradle
Fix dependency checks for CVE-2023-42794 CVE-2023-42795 CVE-2023-45648
> Fix dependency checks for CVE-2023-42794 CVE-2023-42795 CVE-2023-45648

- build.gradle
- config/owasp/suppressions.xml
> fix flyway postgresql

- build.gradle
- config/owasp/suppressions.xml
> add flyway postgresql to buildscript

- config/owasp/suppressions.xml
- infrastructure/app-insights.tf
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-16178
Moving App insight to use the module.
> DTSPO-16178 moving App insight to use module

- src/main/resources/application.yaml
Prevent hikari using using closed connections by sending a keep alive every 5 minutes
> Enable hikari keep alive every 5 mins

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/COT-742
> COT-742: SSCS Camunda Access

- infrastructure/db.tf
- infrastructure/ithc.tfvars
- infrastructure/variables.tf
Upgrade postgresql version 14->15 in place
> Postgresql Upgrade - ITHC

- Jenkinsfile_CNP
Re-syncing perftest branch with master to perform postgres upgrades. This was removed in this pr https://github.com/hmcts/camunda-bpm/pull/740
> Resync perftest with master

- infrastructure/perftest.tfvars
Upgrade postgresql version 14->15 in place
> Postgresql Upgrade - Perftest

- infrastructure/demo.tfvars
Upgrade postgresql version 14->15 in place
> Postgresql Upgrade - Demo

- infrastructure/aat.tfvars
Upgrade postgresql version 14->15 in place
> Postgresql Upgrade - AAT

- infrastructure/prod.tfvars
SKU changed via portal was reset by recent commit. This bumps the SKU back up via code and will cause the flexible server to restart. 
**Should be merged OOH**
> Bump prod sku back up

- Dockerfile
- acb.tpl.yaml
- build.gradle
> Revert "Update hmctspublic.azurecr.io/base/java Docker tag to v21"

- Dockerfile
- acb.tpl.yaml
- build.gradle
[DTSPO-17365](https://tools.hmcts.net/jira/browse/DTSPO-17365)
Upgrading Java 17 to version 21
Tested in ITHC, pods and application started up fine using java 21
> DTSPO-17365 Updating java to version 21

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-578
Adding tenant for Special Tribunals
> DTSSTCI-578

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-17906
- CHG5016746
- Upgrading pgsql version from 14 to 15 in prod
- Upgrade already applied successfully to lower environments
> Upgrade pgsql version in prod

- infrastructure/demo.tfvars
> Bumping SKU

- infrastructure/prod.tfvars
> fix: bump Camunda Prod SQL Storage

- infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18392
Bump SKU in perftest to match prod.
> feat: bump perftest Postgres SKU to match prod

- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
> Scale Back Camunda PSQL Databases Following Data Optimisation

- infrastructure/perftest.tfvars
* Scale Back Camunda PSQL Databases in PerfTest Following Data Optimisation in Preparation for Potential Downsizing on Production
> Scale Back Camunda PSQL Databases Following Data Optimisation (#871)

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17945
Downgrade the database size following recent optimisation activities to save on running costs.
> Downgrade Camunda Prod PostgresSQL Database

- charts/camunda-bpm/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-23130
- Updating chart-java references to the newest release and to the new OCI endpoint.
> Updating chart-java to new OCI endpoint

- build.gradle
- infrastructure/aat.tfvars
- infrastructure/db.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-4705
Enable Azure Query Performance Insight on AAT
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> Enable QPA on AAT
